### ISSUE TITLE
Enable errcheck check-type-assertions in golangci

### ISSUE THREAD

**Issue by fqutishat** [hyperledger/aries-framework-go#151]
```
linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
```
